""" from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch


# Create the client instance
client = Elasticsearch(
    ELASTIC_HTTP,
    ca_certs="/path/to/http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
client.info() """

import os
from elasticsearch import Elasticsearch
from elasticsearch.exceptions import ConnectionError

# Password for the 'elastic' user generated by Elasticsearch
ESENDPOINT=os.getenv('ESENDPOINT')
ESPASSWORD=os.getenv('ESPASSWORD')
ESINDEX=os.getenv('ESINDEX')

def startConnection():
    try:
        # Crea una instancia del cliente apuntando al host de Elasticsearch a través de HTTP
        client = Elasticsearch("http://"+ESENDPOINT+":9200", basic_auth=("elastic", ESPASSWORD), verify_certs=False)
        # Realiza una operación de prueba
        client.info().body
    except ConnectionError as e:
        print("Error de conexion: ", str(e))

startConnection()

print("endpoint: ",ESENDPOINT)
print("password: ",ESPASSWORD)
print("indexName: ",ESINDEX)

