""" from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch


# Create the client instance
client = Elasticsearch(
    ELASTIC_HTTP,
    ca_certs="/path/to/http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
client.info() """

import os
from elasticsearch import Elasticsearch
from elasticsearch.exceptions import ConnectionError
import hashlib
import json

# Password for the 'elastic' user generated by Elasticsearch
ESENDPOINT=os.getenv('ESENDPOINT')
ESPASSWORD=os.getenv('ESPASSWORD')
ESINDEX=os.getenv('ESINDEX')

def startConnection():
    num = 0
    while True:
        try:
            num+=1
            body = '{"brth_yr": 2011, "gndr": "FEMALE", "ethcty": "HISPANIC"}'
            # Crea una instancia del cliente apuntando al host de Elasticsearch a través de HTTP
            json_object = json.loads(body)
            client = Elasticsearch("http://"+ESENDPOINT+":9200", basic_auth=("elastic", ESPASSWORD), verify_certs=False)
            resp = client.index(index=ESINDEX, id=num, document=json_object)
            # Realiza una operación de prueba
            client.info().body
            print("connection successfull")
        except ConnectionError as e:
            print("Error de conexion: ", str(e))

if __name__ == '__main__':
    startConnection()
    print("endpoint: ",ESENDPOINT)
    print("password: ",ESPASSWORD)
    print("indexName: ",ESINDEX)




