 FROM ubuntu:latest

 RUN apt-get update && \
     apt-get upgrade -y
 RUN apt-get update && \
     apt-get install -y curl

 RUN curl -O https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.5.0.deb
 RUN dpkg -i mongodb-database-tools-ubuntu2004-x86_64-100.5.0.deb



